apiVersion: v1
kind: Service
metadata:
    name: {{ include "superfundapi.fullname" . }}
spec:
  type: {{ .Values.service.type }} 
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "superfundapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
